name: cargo-deny

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
  workflow_dispatch:
  schedule:
    - cron: "16 15 * * 3"

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - uses: actions/checkout@v3

      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}
